# BeautifulSoup Web Scraping Example

In [1]:
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup
import urllib.request
import re

In [11]:
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
import time

# 1. Coingecko(CKO) Web Scarping

In [13]:
browser = webdriver.Chrome(executable_path="/Users/kristy/Desktop/BitMart_new/10.爬虫/10.29 button爬虫/chromedriver")
browser.get("https://www.coingecko.com/en/exchanges")

In [14]:
soup = BeautifulSoup(browser.page_source,'html.parser')

In [15]:
def cko():
    rank=[]
    exchange=[]
    trust_score=[]
    volume_normalized=[]
    volume=[]
    website_visits=[]
    coins=[]
    pairs=[]


    for tr in soup.find_all('tr'):
        try:

            tds = tr.find_all('td')
    #         
            if not tds:
                pass
            else:

                rank.append(tds[0].text.strip('\n').strip('\n '))
                exchange.append(tds[1].text.strip('\n').strip('\n').split('\n')[0])
                trust_score.append(tds[2].text.strip('\n').strip('\n '))
                volume_normalized.append(tds[3].text.strip('\n').strip('\n ').strip('$').replace(',',''))
                volume.append(tds[4].text.strip('\n').strip('\n ').strip('\n\n\n\n Trading Incentives').strip('$').replace(',',''))
                website_visits.append(tds[5].text.strip('\n').strip('\n ').replace(',',''))
                coins.append(tds[6].text.strip('\n').strip('\n '))
                pairs.append(tds[7].text.strip('\n').strip('\n '))
        except:
            print('!')
            pass
    
    return rank,exchange,volume_normalized,volume,website_visits

In [16]:
b=cko()

In [17]:
# save to dataframe
cko=pd.DataFrame({'cko_rank':b[0],'exchange':b[1],'cko_24hVolume':b[3],
                  'website_visits':b[4]})

In [62]:
cko['daily_visits']=cko['website_visits'].astype(int)/30
cko['exchange']=cko['exchange'].str.lower()

In [98]:
cko

    cko_rank          exchange cko_24hVolume website_visits   daily_visits
0          1           binance    1652263674       18810000  627000.000000
1          2            kraken     158452326        3091000  103033.333333
2          3          bitfinex     144223813        2867000   95566.666667
3          4           gate.io      66048095        1111000   37033.333333
4          5          poloniex      37533997        1985000   66166.666667
5          6            kucoin      34638586        2074000   69133.333333
6          7           bittrex      19117723        2861000   95366.666667
7          8           bithumb     532921670        7348000  244933.333333
8          9      huobi global    1310477331        2910227   97007.566667
9         10      coinbase pro     254701843        4804000  160133.333333
10        11             upbit     235800579        4906000  163533.333333
11        12          bitstamp     147393297        1839000   61300.000000
12        13          bitflyer      81980243        1110000   37000.000000
13        14           bitbank      34304345        1123000   37433.333333
14        15            gemini      20140180         509028   16967.600000
15        16        ftx (spot)      18964102         232838    7761.266667
16        17          tokenize      16885810         239948    7998.266667
17        18        binance us      16845034         129104    4303.466667
18        19   huobi us (hbus)         88495           5882     196.066667
19        20              okex    1125260127        1368000   45600.000000
20        21            hitbtc    1218301789        1310000   43666.666667
21        22            bigone     940342492        1175000   39166.666667
22        23          coinsbit     363405075        1050000   35000.000000
23        24            hotbit     561825519         610519   20350.633333
24        25           coinone      48210049        1110000   37000.000000
25        26            bitmax     155326148         487355   16245.166667
26        27           bitmart     941017405         331404   11046.800000
27        28              exmo      24264916         894107   29803.566667
28        29          coindeal      19973071         488843   16294.766667
29        30              zaif       9696549        1040000   34666.666667
..       ...               ...           ...            ...            ...
341      342            purcow          0.00           1000      33.333333
342      343      negociecoins          0.00          87271    2909.033333
343      344           novadex          0.00             50       1.666667
344      345         secondbtc        640702              0       0.000000
345      346          cashpayz          5.00              0       0.000000
346      347               uex          0.00           1800      60.000000
347      348         forkdelta         26738              0       0.000000
348      349            dakuce          0.00            350      11.666667
349      350            getbtc          0.00           1000      33.333333
350      351             eosex          0.00            400      13.333333
351      352       coinchangex          0.00           1500      50.000000
352      353      tux exchange          0.00           1100      36.666667
353      354       troca.ninja          0.00           1900      63.333333
354      355  shangya exchange          0.00            500      16.666667
355      356       big markets          0.00              0       0.000000
356      357         coinasset          0.00           3000     100.000000
357      358             koinx          0.00            250       8.333333
358      359           coinhub          0.00           3000     100.000000
359      360            ore bz          0.00            320      10.666667
360      361             9coin          0.00           5901     196.700000
361      362             axnet          0.00            290       9.666667
362      363     dach exchange          0.00           1250      41.666667
363      364         blockonix          0.00           1100      36.666667
364      365            ironex          0.00            300      10.000000
365      366      thinkbit pro          0.00            160       5.333333
366      367   bits blockchain          0.00           3200     106.666667
367      368            koinok          0.00              0       0.000000
368      369             bitc3    0.00000000              0       0.000000
369      370            kairex          0.00            450      15.000000
370      371              btcc    0.00000000           9155     305.166667

[371 rows x 5 columns]

# 2. CoinMarketCap(CMC) Web Scarping

In [21]:
# Get page
page_url='https://coinmarketcap.com/rankings/exchanges/reported/'
page = requests.get(page_url) 
soup = BeautifulSoup(page.content,'html.parser')

In [22]:
# Define a function 

def cmc(n):
    
    
    Rank=[]
    Exchange=[]
    Volume_24h=[]
    Volume_7d=[]
    Volume_30d=[]

    
    
    for i in n:
        j=str(i)
        page_url = "https://coinmarketcap.com/rankings/exchanges/reported/"+j+""
        print(page_url)
        
        page = requests.get(page_url) 

        if page.status_code==200:
            
            soup = BeautifulSoup(page.content, 'html.parser')
    
            
            rank=[]
            exchange=[]
            volume_24h=[]
            volume_7d=[]
            volume_30d=[]



            for tr in soup.find_all('tr'):
                try:

                    tds = tr.find_all('td')
            #         
                    if not tds:
                        pass
                    else:
                        #print(tds[3].text)
                        exchange.append(tds[1].text.strip('\n').strip('\n '))
                        volume_24h.append(tds[2].text.strip('\n').strip('\n ').strip('$').replace(',',''))
                        volume_7d.append(tds[3].text.strip('\n').strip('\n ').strip('$').replace(',',''))
                        volume_30d.append(tds[4].text.strip('\n').strip('\n ').strip('$').replace(',',''))
                        rank.append(tds[0].text.strip('\n').strip('\n '))


                except:
                    print('!')
                    pass
                
        Rank.extend(rank)
        Exchange.extend(exchange)
        Volume_24h.extend(volume_24h)
        Volume_7d.extend(volume_7d)
        Volume_30d.extend(volume_30d)
        

        
        
    return Rank,Exchange,Volume_24h,Volume_7d,Volume_30d

In [23]:
a=cmc(range(1,3))

https://coinmarketcap.com/rankings/exchanges/reported/1
https://coinmarketcap.com/rankings/exchanges/reported/2

In [24]:
# save to dataframe
cmc=pd.DataFrame({'cmc_rank':a[0],'exchange':a[1],'cmc_30dVolume':a[4]})

In [25]:
cmc.count()

cmc_rank         200
exchange         200
cmc_30dVolume    200
dtype: int64

In [65]:
cmc=cmc[['cmc_rank','exchange','cmc_avgVolume']]
cmc['exchange']=cmc['exchange'].str.lower()

In [103]:
cmc.head()

  cmc_rank exchange  cmc_avgVolume
0        1   bitmex   2.455011e+09
1        2      exx   1.147869e+09
2        3     bkex   1.178901e+09
3        4   p2pb2b   9.561889e+08
4        5    lbank   9.525546e+08

# 3. Data Integration

In [67]:
inner=pd.merge(cko,cmc,on='exchange',how='inner')
inner['cko_24hVolume']=inner['cko_24hVolume'].astype(float)

In [68]:
inner.count()

cko_rank          152
exchange          152
cko_24hVolume     152
website_visits    152
daily_visits      152
cmc_rank          152
cmc_avgVolume     152
dtype: int64

In [69]:
inner.head()

,cko_rank,exchange,cko_24hVolume,website_visits,daily_visits,cmc_rank,cmc_avgVolume
0,1,binance,1.652264e+09,18810000,627000.000000,7,1.014083e+09
1,2,kraken,1.584523e+08,3091000,103033.333333,59,1.142067e+08
2,3,bitfinex,1.442238e+08,2867000,95566.666667,63,1.063873e+08
3,4,gate.io,6.604810e+07,1111000,37033.333333,81,4.787212e+07
4,5,poloniex,3.753400e+07,1985000,66166.666667,92,2.320810e+07

In [70]:
# Average
inner['avg']=(inner['cko_24hVolume'] + inner['cmc_avgVolume'])/2

In [71]:
# Calculate ADUTV
inner['ADUTV']=inner['avg']/inner['daily_visits']

In [101]:
inner.loc[inner['exchange'].isin(['binance', 'bitfinex', 'kraken', 
                                'bitstamp', 'coinbase pro', 'bitflyer',
                                'gemini', 'itbit', 'bittrex', 
                                'poloniex'])].reset_index(drop=True)

,cko_rank,exchange,cko_24hVolume,website_visits,daily_visits,cmc_rank,cmc_avgVolume,avg,ADUTV,adjust_volume
0,1,binance,1.652264e+09,18810000,627000.000000,7,1.014083e+09,1.333173e+09,2126.273150,8.296207e+08
1,2,kraken,1.584523e+08,3091000,103033.333333,59,1.142067e+08,1.363295e+08,1323.159076,1.323159e+03
2,3,bitfinex,1.442238e+08,2867000,95566.666667,63,1.063873e+08,1.253056e+08,1311.184801,1.311185e+03
3,5,poloniex,3.753400e+07,1985000,66166.666667,92,2.320810e+07,3.037105e+07,459.008273,4.590083e+02
4,7,bittrex,1.911772e+07,2861000,95366.666667,113,2.006576e+07,1.959174e+07,205.435950,2.054360e+02
5,10,coinbase pro,2.547018e+08,4804000,160133.333333,53,1.813240e+08,2.180129e+08,1361.446131,2.118819e+08
6,12,bitstamp,1.473933e+08,1839000,61300.000000,62,1.096511e+08,1.285222e+08,2096.609799,8.110965e+07
7,13,bitflyer,8.198024e+07,1110000,37000.000000,75,4.171576e+07,6.184800e+07,1671.567663,4.895689e+07
8,15,gemini,2.014018e+07,509028,16967.600000,110,1.463846e+07,1.738932e+07,1024.854431,1.024854e+03
9,83,itbit,1.051770e+07,22789,759.633333,124,8.960575e+06,9.739138e+06,12820.840735,1.005116e+06

In [99]:
# Calculate Benchmark
bench=np.median(inner['ADUTV'].loc[inner['exchange'].isin(['binance', 'bitfinex', 'kraken', 
                                                           'bitstamp', 'coinbase pro', 'bitflyer',
                                                           'gemini', 'itbit', 'bittrex', 
                                                           'poloniex'])])

In [100]:
bench

1342.302603370146

In [78]:
adjust_volume=[]
for i,j in zip(inner['ADUTV'],inner['daily_visits']):
    if i<= bench:
        adjust_volume.append(i)
    else:
        adjust_volume.append (bench*j)

In [79]:
inner['adjust_volume']=adjust_volume

In [157]:
inner=inner[['cko_rank','cmc_rank','exchange','website_visits','adjust_volume']]

In [159]:
inner.count()

cko_rank          152
cmc_rank          152
exchange          152
website_visits    152
adjust_volume     152
dtype: int64